{
 "title": "Site Title",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Site_ID", "query": "${VAR_SITE_ID}" },
   {
    "name": "Site_ID",
    "query": "SELECT inverterID FROM installation WHERE siteID=$Site_ID"
   },
   {
    "name": "Site_Inverter_ID1",
    "query": "SELECT inverterID FROM installation WHERE siteID=$Site_ID LIMIT 1"
   },
   {
    "name": "Site_Inverter_ID2",
    "query": "SELECT inverterID FROM installation WHERE siteID=$Site_ID LIMIT 1,1"
   },
   { "name": "StatusHuaweiOK", "query": "${VAR_STATUSHUAWEIOK}" },
   {
    "name": "interval",
    "query": "select 'minute' AS __text, '%Y%m%d%H%i' as __value union select 'hour' AS __text, '%Y%m%d%H' as __value union select 'day' AS __text, '%Y%m%d' as __value union select 'month' AS __text, '%Y%m' as __value union select 'year' AS __text, '%Y' as __value"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Energy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  MAX(UNIX_TIMESTAMP(dateAndTime)) as time_sec,\n  MAX(WattHours)/1000.0 as value\nFROM viewTotalEnergy\nWHERE $__timeFilter(dateAndTime)\nGROUP BY date_format(dateAndTime, \"${interval}\")\nORDER BY date_format(dateAndTime, \"${interval}\") ASC"
    }
   ]
  },
  {
   "title": "Max. Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  dateAndTime AS \"time\",\n  temp\nFROM sample\nWHERE\n  $__timeFilter(dateAndTime)\nORDER BY dateAndTime"
    }
   ]
  },
  {
   "title": "Power [kW]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  dateAndTime AS \"time\",\n  SUM(pac)/1000.0 AS \"kW (Total)\"\nFROM sample\nWHERE\n  $__timeFilter(dateAndTime) AND\n  inverterID IN (SELECT inverterID FROM installation WHERE siteID=$Site_ID)\nGROUP BY dateAndTime\nORDER BY dateAndTime"
    },
    {
     "rawSql": "SELECT\n  dateAndTime AS \"time\",\n  pac/1000.0 AS \"kW (Inverter 1)\"\nFROM sample\nWHERE\n  $__timeFilter(dateAndTime) AND\n  inverterID=$Site_ID\nGROUP BY dateAndTime\nORDER BY dateAndTime"
    },
    {
     "rawSql": "SELECT\n  dateAndTime AS \"time\",\n  pac/1000.0 AS \"kW (Inverter 2)\"\nFROM sample\nWHERE\n  $__timeFilter(dateAndTime) AND\n  inverterID=$Site_Inverter_ID2\nGROUP BY dateAndTime\nORDER BY dateAndTime"
    }
   ]
  },
  {
   "title": "Current Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  dateAndTime AS \"time\",\n  status\nFROM sample\nWHERE\n  $__timeFilter(dateAndTime) AND\n  inverterID=$Site_Inverter_ID1\nORDER BY dateAndTime"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  dateAndTime AS \"time\",\n  uac\nFROM sample\nWHERE\n  $__timeFilter(dateAndTime)\nORDER BY dateAndTime"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  dateAndTime AS \"time\",\n  uac\nFROM sample\nWHERE\n  $__timeFilter(dateAndTime) AND\n  status=$StatusHuaweiOK\nORDER BY dateAndTime"
    }
   ]
  }
 ]
}